server.port: 8080
server.session.timeout: 86400
server.servlet.context-path: "/server-test"
spring.datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    validation-query: "SELECT 1;"


spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate:
    temp.use_jdbc_metadata_defaults: false
    order_inserts: true
    order_updates: true
    jdbc:
      batch_size: 20
      batch_versioned_data: true

spring.liquibase:
    change-log: classpath:liquibase/migration.yml
    contexts: common
    default-schema: servertest

security.jwt.token:
    expire-length: 300
    secret-key: secret-key

